

CREATE TABLE OFICINAS
(COD_OFICINA INT,
COD_DIRECTOR INT,
DESCRIPCION VARCHAR (100),
PRIMARY KEY (COD_OFICINA)
);
INSERT INTO OFICINAS VALUES (1, 100, 'Oficina Central Buenos Aires');
INSERT INTO OFICINAS VALUES (2, 101, 'Sucursal Córdoba');
INSERT INTO OFICINAS VALUES (3, 102, 'Sucursal Rosario');
INSERT INTO oficinas VALUES (4,NULL,'Sucursal Mendoza');


CREATE TABLE DOCUMENTOS
(COD_DOCUMENTO INT,
DESCRIPCION VARCHAR (100),
PRIMARY KEY(COD_DOCUMENTO)
);
INSERT INTO DOCUMENTOS VALUES (1, 'DNI');
INSERT INTO DOCUMENTOS VALUES (2, 'Pasaporte');
INSERT INTO DOCUMENTOS VALUES (3, 'Libreta Cívica');


CREATE TABLE EMPLEADOS (  
COD_EMPLEADO INT,  
APELLIDO VARCHAR(30),  
NOMBRE VARCHAR(30),  
FECHA_NACIMIENTO DATE,  
NUM_DOCUMENTO INT,  
COD_JEFE INT,  
COD_OFICINA INT,  
COD_DOCUMENTO INT,  
PRIMARY KEY (COD_EMPLEADO),  
FOREIGN KEY (COD_JEFE) REFERENCES EMPLEADOS (COD_EMPLEADO),  
FOREIGN KEY (COD_OFICINA) REFERENCES OFICINAS (COD_OFICINA),  
FOREIGN KEY (COD_DOCUMENTO) REFERENCES DOCUMENTOS (COD_DOCUMENTO)  
);  
INSERT INTO EMPLEADOS VALUES (100, 'González', 'María', '1980-05-15', 22333444, NULL, 1, 1);
INSERT INTO EMPLEADOS VALUES (101, 'Pérez', 'Juan', '1985-03-22', 25444555, 100, 2, 1);
INSERT INTO EMPLEADOS VALUES (102, 'Rodríguez', 'María', '1990-11-30', 28888999, 100, 3, 2);
INSERT INTO EMPLEADOS VALUES (103, 'López', 'Carlos', '1992-07-19', 29999111, 101, 2, 2);


CREATE TABLE DATOS_CONTRATOS(
COD_EMPLEADO INT,
FECHA_CONTRATO DATE,
CUOTA INT,
VENTA INT,
PRIMARY KEY (COD_EMPLEADO, FECHA_CONTRATO),
FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADOS (COD_EMPLEADO)
);
INSERT INTO DATOS_CONTRATOS VALUES (100, '2009-01-10', 150000, 50000);
INSERT INTO DATOS_CONTRATOS VALUES (101, '2021-03-12', 120000, 30000);
INSERT INTO DATOS_CONTRATOS VALUES (102, '2016-06-01', 300000, 40000);
INSERT INTO DATOS_CONTRATOS VALUES (103, '2010-08-05', 80000, 25000);


CREATE TABLE FABRICANTES(
COD_FABRICANTE INT,
RAZON_SOCIAL VARCHAR (100),
PRIMARY KEY (COD_FABRICANTE)
);
INSERT INTO FABRICANTES VALUES (1, 'Tecnología SA');
INSERT INTO FABRICANTES VALUES (2, 'ElectroGlobal SRL');
INSERT INTO FABRICANTES VALUES (3, 'Componentes del Sur');


CREATE TABLE LISTAS(
COD_LISTA INT,
DESCRIPCION VARCHAR (100),
GANANCIAS FLOAT,
PRIMARY KEY (COD_LISTA)
);
INSERT INTO LISTAS VALUES (1, 'Lista Minorista', 15.5);
INSERT INTO LISTAS VALUES (2, 'Lista Mayorista', 10.0);
INSERT INTO LISTAS VALUES (3, 'Lista Premium', 20.0);


CREATE TABLE PRODUCTOS(
COD_PRODUCTO INT,
DESCRIPCION VARCHAR (100),
PRECIO FLOAT,
CANTIDAD_STOCK INT,
PUNTO_REPOSICION INT,
COD_FABRICANTE INT,
PRIMARY KEY (COD_PRODUCTO),
FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES (COD_FABRICANTE)
);
INSERT INTO PRODUCTOS VALUES (101, 'Notebook HP', 600000.00, 3, 5, 1);
INSERT INTO PRODUCTOS VALUES (102, 'Mouse Logitech', 5000.00, 50, 10, 2);
INSERT INTO PRODUCTOS VALUES (103, 'Teclado Redragon', 8000.00, 20, 5, 2);
INSERT INTO PRODUCTOS VALUES (104, 'Monitor Samsung 24"', 75000.00, 3, 5, 3);


CREATE TABLE PRECIOS(
COD_PRODUCTO INT,
COD_LISTA INT,
PRECIO FLOAT,
PRIMARY KEY (COD_PRODUCTO, COD_LISTA),
FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS (COD_PRODUCTO),
FOREIGN KEY (COD_LISTA) REFERENCES LISTAS (COD_LISTA)
);
INSERT INTO PRECIOS VALUES (101, 1, 600000.00);
INSERT INTO PRECIOS VALUES (101, 2, 580000.00);
INSERT INTO PRECIOS VALUES (102, 1, 5000.00);
INSERT INTO PRECIOS VALUES (102, 3, 4500.00);
INSERT INTO PRECIOS VALUES (103, 2, 7600.00);
INSERT INTO PRECIOS VALUES (104, 1, 75000.00);
INSERT INTO PRECIOS VALUES (104, 3, 72000.00);


CREATE TABLE CLIENTES(
COD_CLIENTE INT,
COD_LISTA INT,
RAZON_SOCIAL VARCHAR (100),
PRIMARY KEY (COD_CLIENTE),
FOREIGN KEY (COD_LISTA) REFERENCES LISTAS (COD_LISTA)
);
INSERT INTO CLIENTES VALUES (1, 1, 'L.Distribuidora Norte');
INSERT INTO CLIENTES VALUES (2, 2, 'L.Mayorista Centro');
INSERT INTO CLIENTES VALUES (3, 3, 'Comercial Sur');



CREATE TABLE PEDIDOS (
COD_PEDIDO INT,
FECHA_PEDIDO DATE NOT NULL,
COD_EMPLEADO INT,
COD_CLIENTE INT,
PRIMARY KEY (COD_PEDIDO),
FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADOS (COD_EMPLEADO),
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES (COD_CLIENTE)
);
INSERT INTO PEDIDOS VALUES (2001, '2025-03-01', 101, 1);
INSERT INTO PEDIDOS VALUES (2002, '2025-03-15', 102, 2);
INSERT INTO PEDIDOS VALUES (2003, '2025-04-20', 103, 3);


CREATE TABLE DETALLE_PEDIDOS(
COD_PEDIDO INT,
NUMERO_LINEA INT,
COD_PRODUCTO INT,
CANTIDAD INT NOT NULL,
PRIMARY KEY (NUMERO_LINEA, COD_PRODUCTO),
FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDOS  (COD_PEDIDO),
FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS (COD_PRODUCTO)
);
INSERT INTO DETALLE_PEDIDOS VALUES (2001, 1, 101, 1);
INSERT INTO DETALLE_PEDIDOS VALUES (2001, 2, 102, 2);
INSERT INTO DETALLE_PEDIDOS VALUES (2002, 1, 104, 1);
INSERT INTO DETALLE_PEDIDOS VALUES (2003, 1, 103, 3);
INSERT INTO DETALLE_PEDIDOS VALUES (2003, 2, 102, 1);

/*consultas simples*/
SELECT O.DESCRIPCION AS NOMBRE_OFICINAS
FROM oficinas O;

SELECT P.DESCRIPCION AS PRODUCTO,
PRECIO AS PRECIO_BASE, 
(PRECIO+(PRECIO*0.21)) AS IVA_INCLUIDO
FROM productos P;

SELECT E.APELLIDO,
E.NOMBRE, 
E.FECHA_NACIMIENTO,
YEAR (CURDATE())-YEAR(E.FECHA_NACIMIENTO) AS  EDAD
FROM empleados E
WHERE E.COD_JEFE IS NOT NULL;

SELECT E.NOMBRE,
E.APELLIDO AS LISTADO_EMPLEADOS
FROM empleados E
WHERE COD_JEFE IS NOT NULL;

SELECT E.NOMBRE, E.APELLIDO  
FROM empleados E  
WHERE E.NOMBRE = 'Maria' 
AND E.COD_JEFE IS NOT NULL 
ORDER BY E.APELLIDO;  

SELECT C.RAZON_SOCIAL AS LISTA_RAZON_SOCIAL,
C.COD_CLIENTE AS CODIGO_CLIENTE
FROM clientes C
WHERE C.RAZON_SOCIAL LIKE 'L%'
ORDER BY C.COD_CLIENTE;

SELECT PE.FECHA_PEDIDO,
PE.COD_PEDIDO,
PE.COD_EMPLEADO,
PE.COD_CLIENTE AS LISTA_PEDIDOS
FROM pedidos PE
WHERE PE.FECHA_PEDIDO>='2025-03-01' 
AND PE.FECHA_PEDIDO<='2025-03-31'
ORDER BY PE.FECHA_PEDIDO;

SELECT O.DESCRIPCION AS LISTA_OFICINAS
FROM oficinas O
WHERE O.COD_DIRECTOR IS NULL;

SELECT P.DESCRIPCION,
P.PRECIO AS LISTA_MENOR_PRECIO
FROM productos P
ORDER BY P.PRECIO ASC
LIMIT 4;

SELECT DC.COD_EMPLEADO,
DC.CUOTA AS LISTA_MAYOR_CUOTA
FROM datos_contratos DC
ORDER BY DC.CUOTA DESC
LIMIT 3;
 
 /*Cconsultas multitablas*/
 SELECT P.DESCRIPCION AS PRODUCTO,
 F.RAZON_SOCIAL AS FABRICANTE,
 P.CANTIDAD_STOCK AS CANTIDAD
 FROM productos P, fabricantes F
 WHERE P.COD_FABRICANTE=F.COD_FABRICANTE
 ORDER BY F.RAZON_SOCIAL, P.DESCRIPCION;
 
 SELECT PE.COD_PEDIDO AS PEDIDO, 
 PE.FECHA_PEDIDO AS FECHA, E.APELLIDO AS EMPLEADO_A_CARGO, 
 C.RAZON_SOCIAL AS CLIENTE
 FROM pedidos PE, empleados E, clientes C
 WHERE PE.COD_EMPLEADO = E.COD_EMPLEADO
 AND PE.COD_CLIENTE = C.COD_CLIENTE;
 
 SELECT E.APELLIDO AS EMPLEADO,
 DC.CUOTA AS CUOTA_ASIGNADA,
 O.DESCRIPCION AS OFICINA 
 FROM empleados E, datos_contratos DC, oficinas O
 WHERE E.COD_EMPLEADO=DC.COD_EMPLEADO
 AND E.COD_OFICINA=O.COD_OFICINA
 AND E.COD_JEFE IS NOT NULL
 ORDER BY DC.CUOTA DESC;

SELECT DISTINCT CL.RAZON_SOCIAL AS CLIENTES,
PE.FECHA_PEDIDO AS FECHA
FROM CLIENTES CL, PEDIDOS PE
WHERE CL.COD_CLIENTE = PE.COD_CLIENTE
AND PE.FECHA_PEDIDO >='2025-04-01'
AND PE.FECHA_PEDIDO<='2025-04-30';

SELECT DISTINCT PE.FECHA_PEDIDO AS FECHAS,
PR.DESCRIPCION AS PRODUCTOS
FROM detalle_pedidos DT, productos PR, pedidos PE
WHERE DT.COD_PEDIDO=PE.COD_PEDIDO
AND DT.COD_PRODUCTO=PR.COD_PRODUCTO
AND PE.FECHA_PEDIDO >= '2025-03-01'
AND PE.FECHA_PEDIDO <= '2025-03-31';

SELECT E.NOMBRE AS NOMBRE_EMPLEADO, 
E.APELLIDO AS APELLIDO_EMPLEADO,
DC.FECHA_CONTRATO AS AÑO_CONTRATADO
FROM empleados E, datos_contratos DC
WHERE E.COD_EMPLEADO=DC.COD_EMPLEADO
AND E.COD_JEFE IS NOT NULL
AND TIMESTAMPDIFF(YEAR, DC.FECHA_CONTRATO, CURDATE()) > 10
ORDER BY DC.FECHA_CONTRATO DESC;

SELECT CL.RAZON_SOCIAL,
L.DESCRIPCION AS MAYORISTA
FROM listas L, clientes CL 
WHERE L.DESCRIPCION LIKE '%MAYORISTA%'
ORDER BY CL.RAZON_SOCIAL;

SELECT DISTINCT PR.DESCRIPCION AS PRODUCTO, CL.RAZON_SOCIAL AS CLIENTE
FROM productos PR, clientes CL, pedidos PE, detalle_pedidos DT 
WHERE CL.COD_CLIENTE=PE.COD_CLIENTE
AND PE.COD_PEDIDO=DT.COD_PEDIDO
AND DT.COD_PRODUCTO=PR.COD_PRODUCTO
ORDER BY CL.RAZON_SOCIAL, DESCRIPCION;

SELECT PR.DESCRIPCION AS PRODUCTO,
FA.RAZON_SOCIAL AS FABRICANTE,
DT.CANTIDAD AS CANTIDAD_PRODUCTO
FROM productos PR, fabricantes FA, detalle_pedidos DT
WHERE PR.COD_FABRICANTE=FA.COD_FABRICANTE
AND PR.COD_PRODUCTO=DT.COD_PRODUCTO
AND PR.CANTIDAD_STOCK < PR.PUNTO_REPOSICION
ORDER BY PR.DESCRIPCION, FA.RAZON_SOCIAL;


SELECT E.APELLIDO AS EMPLEADO,
DT.CUOTA AS CUOTA
FROM empleados E, datos_contratos DT
WHERE E.COD_EMPLEADO=DT.COD_EMPLEADO 
AND (DT.CUOTA < 50000 OR DT.CUOTA > 100000)
AND E.COD_JEFE IS NOT NULL;