
CREATE TABLE CLIENTES(
CODIGO_CLIENTE INT,
NOMBRE VARCHAR (100) NOT NULL,
DOMICILIO VARCHAR (100) NOT NULL,
PROVINCIA VARCHAR (100) NOT NULL,
PRIMARY KEY (CODIGO_CLIENTE)
);
INSERT INTO CLIENTES VALUES
(1, 'Juan Pérez', 'Calle Falsa 123', 'Buenos Aires'),
(2, 'María Gómez', 'Av. Siempre Viva 742', 'Córdoba'),
(3, 'Carlos Ruiz', 'Mitre 456', 'Mendoza'),
(4, 'Laura Díaz', 'Rivadavia 100', 'Santa Fe'),
(5, 'Pedro Álvarez', 'Belgrano 55', 'Salta');

CREATE TABLE PRODUCTOS (
CODIGO_PRODUCTO INT,
NOMBRE_PRODUCTO VARCHAR (100) NOT NULL,
PRIMARY KEY (CODIGO_PRODUCTO)
);
INSERT INTO PRODUCTOS VALUES
(101, 'Notebook Lenovo'),
(102, 'Mouse Logitech'),
(103, 'Teclado Redragon'),
(104, 'Monitor Samsung 24"'),
(105, 'Auriculares Sony');

CREATE TABLE ITEM_VENTAS (
NUMERO_FACTURA INT,
CODIGO_PRODUCTO INT,
CANTIDAD INT NOT NULL,
PRECIO FLOAT NOT NULL ,
PRIMARY KEY (NUMERO_FACTURA, CODIGO_PRODUCTO),
FOREIGN KEY (NUMERO_FACTURA) REFERENCES VENTAS (NUMERO_FACTURA),
FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTOS(CODIGO_PRODUCTO) 
);
INSERT INTO VENTAS VALUES
(1001, 1, '2025-05-01'),
(1002, 2, '2025-05-02'),
(1003, 3, '2025-05-02'),
(1004, 1, '2025-05-03'),
(1005, 4, '2025-05-03');

CREATE TABLE VENTAS (
NUMERO_FACTURA INT,
CODIGO_CLIENTE INT,
FECHA DATE  NOT NULL,
PRIMARY KEY (NUMERO_FACTURA),
FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO_CLIENTE)
);
INSERT INTO ITEM_VENTAS VALUES
(1001, 101, 31, 600000.00),
(1001, 102, 15, 15000.00),
(1002, 103, 1, 20000.00),
(1003, 104, 1, 90000.00),
(1003, 105, 2, 30000.00),
(1004, 101, 1, 600000.00),
(1005, 105, 1, 15000.00),
(1005, 102, 1, 7500.00),
(1002, 105, 1, 15000.00),
(1004, 103, 2, 40000.00);


SELECT MAX(IV.CANTIDAD) AS CANTIDAD_MAXIMA,
PR.NOMBRE_PRODUCTO AS PRODUCTO
FROM item_ventas IV, productos PR
WHERE IV.CODIGO_PRODUCTO=PR.CODIGO_PRODUCTO;

SELECT SUM(IV.CANTIDAD) AS CANTIDAD_TOTAL,
PR.NOMBRE_PRODUCTO AS PRODUCTO
FROM item_ventas IV, productos PR
WHERE PR.CODIGO_PRODUCTO=103;

SELECT SUM(IV.CANTIDAD) AS UNIDADES_VENDIDAS,
PR.NOMBRE_PRODUCTO AS PRODUCTO
FROM productos PR, item_ventas IV
WHERE IV.CODIGO_PRODUCTO=PR.CODIGO_PRODUCTO
GROUP BY PR.NOMBRE_PRODUCTO
ORDER BY UNIDADES_VENDIDAS DESC;
 
SELECT PR.NOMBRE_PRODUCTO AS PRODUCTO_VENDIDO,
SUM(IV.CANTIDAD) AS CANTIDAD_VENDIDA
FROM item_ventas IV, productos PR
WHERE IV.CODIGO_PRODUCTO=PR.CODIGO_PRODUCTO
GROUP BY PR.NOMBRE_PRODUCTO
HAVING SUM(IV.CANTIDAD)>30
ORDER BY PR.NOMBRE_PRODUCTO;

SELECT C.CODIGO_CLIENTE AS CODIGO_CLIENTE,
C.NOMBRE AS CLIENTE,
COUNT(V.NUMERO_FACTURA) AS CANTIDAD_COMPRAS
FROM ventas V, clientes C
WHERE C.CODIGO_CLIENTE=V.CODIGO_CLIENTE
GROUP BY C.NOMBRE, C.CODIGO_CLIENTE
ORDER BY C.NOMBRE, C.CODIGO_CLIENTE;

SELECT AVG(IV.CANTIDAD) AS PROMEDIO_UNIDADES,
IV.CODIGO_PRODUCTO AS PRODUCTO
FROM ventas V, item_ventas IV
WHERE V.NUMERO_FACTURA=IV.NUMERO_FACTURA
AND V.CODIGO_CLIENTE=1
GROUP BY IV.CODIGO_PRODUCTO;
